#!/usr/bin/env python3
"""Apply chronicle scene lyric adaptations. ♪ lines keep text-only; vocals get `scene`."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "src/lib/data/lyrics"
NOTE = "♪"

# vocal-index → scene line (parallel to non-♪ lines only)
SCENES: dict[str, list[str]] = {}

# ── Bidam · Never See Me Again (Kanye crashout → rebel vindication) ──
SCENES["ePqZ9BPNsv8"] = [
	"And it'll be a long time, before you ever see me again, me again",
	"They want me, hold my head in shame",
	"The council just called, say I'm insane",
	"And then the marshal told me \"Put down the sword, dog\"",
	"I need a little something to knock the edge off",
	"Feel like I'm all alone and Surabol sucks",
	"I think we need a god need to guide us",
	"Surrounded by fakes, need more riders",
	"I'm hoping that truth that's inside us",
	"See, I need some time to meditate",
	"Naw — I'm True Bone, I need time to levitate",
	"And I'm a heavyweight, you a featherweight",
	"And I'm very great, rocking in every gate",
	"Do not debate, you cannot cape",
	"Even all the way back then I was different",
	"Guess it's my fate, guess it was written",
	"Now I'm speaking, everybody's face spitting",
	"Don't worry 'bout me, worry 'bout you",
	"Worry 'bout something that we can't do",
	"And motherfuckers, it'll be a long time",
	"Before you ever see me again",
	"Don't worry 'bout me, worry 'bout you",
	"Worry about something, don't worry what I do",
	"Hatin' motherfuckers, it'll be a long time",
	"Before you ever see me again, me again",
	"Don't worry about what I been up to",
	"Where the fuck I'm going — nah, court, fuck you",
	"Who the fuck is asking? I'ma be the last standing",
	"And who gonna run the country?",
	"So if everybody just stand now, and shit don't pan out",
	"Throw your hands up, at least give them a handout",
	"I'ma be an icon, like the old kings is",
	"I'ma keep on fighting til the days I'm headless",
	"Or feeling like Bidam at the end of the siege",
	"Where you took me to five more mornings just to get to me",
	"Or feeling like I still got it",
	"So I guess the only problem is you still not it",
	"Or maybe if history go and say I'm that man",
	"Or maybe damn, I could just write my name through thinner",
	"Maybe I should stop being real, maybe I should bow quieter",
	"And I'ma drink 'til the sun up, 'til I got no more liver",
	"Can you clap your hands, hands?",
	"Clap your, clap your hand, hands",
	"Clap your, clap your hand, hands",
	"And I wanna do something, I wanna do something then",
	"Can you clap your hand, hands?",
	"Need you to clap your hands, hands",
	"Need you to clap your hands, hands",
	"Need you to clap your hands",
	"Need you to clap your hands",
	"Don't worry 'bout me, worry 'bout you",
	"Worry 'bout something that we can't do",
	"And motherfuckers, it'll be a long time",
	"Before you ever see me again",
	"Don't worry 'bout me, worry 'bout you",
	"Worry about something, don't worry what I do",
	"Hatin' motherfuckers, it'll be a long time",
	"Before you ever see me again, me again",
	"I guess it's a small court after all",
	"I ran the night 'cause it's a small world after all",
	"And feeling like you got it all?",
	"Nah, marshal — not at all",
	"Last summer, last fight, and y'all had a fall out",
	"Y'all had your ups and downs, I don't fuck around",
	"Y'all feelings felt something, y'all don't feel nothing now",
	"Her tears dried up, your face lookin' expressionless",
	"And I'ma stand and deliver 'til I float down the river",
	"And I'ma spit it, like I meant it, for myself, but I dunna",
	"I'd rather live by what I live by 'til my very last breath",
	"'Cause you know what? A coward dies a thousand deaths",
	"And I promise this time I'ma right my steps",
	"And I probably could make a ride down to hell with this",
	"You can't style on me — I'm out of your league",
	"I'm liable to be a liability",
	"Don't worry 'bout me, worry 'bout you",
	"Worry 'bout something that we can't do",
	"And motherfuckers, it'll be a long time",
	"Before you ever see me again",
	"Don't worry 'bout me, worry 'bout you",
	"Worry about something, don't worry what I do",
	"Hatin' motherfuckers, it'll be a long time",
	"Before you ever see me again, me again (ever see me again)",
	"Me again (ever see me again — history will)",
	"It'll be a long time",
	"Before you ever see me again (ever see me again)",
	"Me again",
]

# ── Jumong · 너를 위해 (Sosuno + Haemosu in the sky + founding) ──
SCENES["-YQ247p0Wt8"] = [
	"어쩜 우린 복잡한 인연에",
	"하늘과 땅에 엉켜 있는 사람인가 봐",
	"나는 매일 네게 갚지도 못할 만큼 많은",
	"빚을 지고 있어 — 아버지, 그리고 너",
	"연인처럼 때론 남남처럼",
	"계속 살아가도 괜찮은 걸까",
	"그렇게도 많은 잘못과 잦은 이별에도",
	"항상 거기 있는 너",
	"날 세상에서 제대로 살게 해줄",
	"유일한 사람이 너란 걸 알아 — 소서노",
	"나 후회 없이 살아가기 위해",
	"너를 붙잡아야 할 테지만",
	"내 거친 생각과 불안한 눈빛과",
	"그걸 지켜보는 너",
	"그건 아마도 전쟁 같은 사랑",
	"난 위험하니까 사랑하니까",
	"너에게서 떠나 줄꺼야 — 아니, 가지 마",
	"날 세상에서 제대로 살게 해줄",
	"유일한 사람이 너란 걸 알아",
	"나 후회 없이 살아가기 위해",
	"너를 붙잡아야 할 테지만",
	"내 거친 생각과 불안한 눈빛과",
	"하늘이 지켜보는 너",
	"그건 아마도 (건국 같은 사랑)",
	"(난) 위험하니까 사랑하니까",
	"너와 함께 갈 테야",
	"Oh-ooh-oh-ooh-oh-ooh-oh",
	"너를 위해 — 아버지를 위해",
	"(새 나라를)",
	"감사합니다 (hoo)",
]

# ── Bupmin · You Know Better Than I (unify Samhan) ──
SCENES["3jJJcacnGVI"] = [
	"I thought I did what's right",
	"I thought I had the answers",
	"I thought I chose the surest road",
	"But that road brought me here — three kingdoms",
	"So I put up a fight",
	"And told Heaven how to help me",
	"Now just when I have given up",
	"The truth is coming clear",
	"You know better than I",
	"You know the way — one Samhan",
	"I've let go the need to know why",
	"For You know better than I",
	"If this has been a test — Ansi, Sabi, the fall",
	"I cannot see the reason",
	"But maybe knowing I don't know",
	"Is part of getting through",
	"I try to do what's best",
	"And faith has made it easy",
	"To see the best thing I can do",
	"Is put my trust in You — and finish it",
	"For You know better than I",
	"You know the way",
	"I've let go the need to know why",
	"For You know better than I",
	"I saw one cloud and thought it was a sky",
	"I saw a bird and thought that I could follow",
	"But it was You who taught that bird to fly",
	"If I let You reach me will You teach me — unify",
	"For You know better than I",
	"You know the way",
	"I've let go the need to know why",
	"I'll take what answers You supply",
	"You know better than I",
	"You know better than I",
	"You know the way — Samhan one",
	"You know better than I",
]

# ── Fall of Joseon · mother to baby among Tang soldiers ──
# ASR is junk — write clean Korean scene lines for each slot
SCENES["ekghP2_w8h8"] = [
	"울지 마, 아가",
	"떨어지는",
	"눈물은",
	"엄마가",
	"다 받을게",
	"슬프기 때문에 우는 거 알아 — 그래도 울지 마",
	"아가",
	"중국 병사가 듣고 있어",
	"때문에",
	"장파가 피가",
	"내려도",
	"사랑만은 우리 손에",
	"서네요 — 마음에 파도를 맞아요",
	"숙여요, 우리",
	"둘만의 숨소리",
	"때문에 — 이 시간이 지나고",
	"또 지나 살아",
	"추워도 온 마음을 열고 나은 내가",
	"되어요 — 뜨거운 눈으로 씻어요",
	"씻어요, 이젠",
	"뒤돌아서서도",
	"고개는",
	"들어요 — 대련 설움에 아빠 올 줄",
	"모르고",
	"이런 순간들을",
	"견뎠어 — 존다 왔고 왔던",
	"지난날의 이야기 속에",
	"우리",
	"이제는 떠나야",
	"하나요 — 이 시간을 지나고 또 지나",
	"햇살이",
	"비추면 온 마음 열게 나은 내가",
	"되어요 — 뜨거운 마음으로 눈물을 적셔요",
	"슬픔을 적셔요",
	"이젠 뒤돌아서서",
	"고개를",
	"들어요 — 이 시간이 지나고",
	"또 지나 햇살이",
	"피면 온 마음을 열고 나은 내가",
	"되어요 — 뜨거운 마음으로 눈물을 적셔요",
	"슬픔을 적셔요",
	"이젠",
	"뒤돌아서서 고개를",
	"들어요",
	"돌아서서",
	"들어요 — 우리 백성은 다시 일어선다",
]

# ── Chunchu revenge · destroy Baekje, never give up ──
SCENES["RKJNMmQFz4U"] = [
	"아무 때고 백제에 칼 대도",
	"나야 하며 말을 꺼내도",
	"누군지 한 번에 알아낼",
	"나의 단 한 원수",
	"사비 성에 걸린 깃발을 보면",
	"제일 먼저 내가 떠올릴 이름",
	"나의 가슴 속에 항상 간직될 이름",
	"내게 그런 원수가 나일 순 없는지",
	"네 곁에 있는 내 친구가 아니라",
	"언젠가 백제가 너를 맘 아프게 해",
	"너 혼자 울고 있는걸 봤어 — 외숙모",
	"달려가 그들에게 나 이 말 해줬으면",
	"그대가 울리는 그 한 나라가",
	"내겐 삶의 전부라고 — 아니, 없애야 할",
	"혼자서는 힘든 복수가 오면",
	"제일 먼저 내가 찾아 줄 칼",
	"나의 생일마다 꽃 대신 피 안겨 줄",
	"내게 그런 사람이 나일 순 없는지",
	"네 곁에 있는 내 친구가 아니라",
	"언젠가 백제가 너를 맘 아프게 해",
	"너 혼자 울고 있는걸 봤어",
	"달려가 그들에게 나 이 말 해줬으면",
	"나의 일생을 모두 주어도",
	"난 포기 못하는",
	"백제를 가진 그대라고 — 무너뜨릴",
	"백제를 곁에 둔 이유만으로",
	"다른 이 세상 누구보다",
	"난 멈추지 않는 거라고",
	"언젠가 백제가 너를 맘 아프게 해",
	"너 혼자 울고 있는걸 봤어",
	"달려가 그들에게 나 이 말 해줬으면 — 끝장낼게",
]

# ── Euija ambition · win court + Samhan ──
SCENES["knb13a6oaLA"] = [
	"한참 동안을 찾아가지 않은",
	"저 의자 너머 조정엔",
	"오래 전 그 왕좌 그대로 난",
	"서 있을 것 같아",
	"내 기억보다는 오래돼버린 얘기지 — 씨족들",
	"날 보던 나의 그 모습",
	"이제는 내가 널 피하려고 하나 — 아니",
	"언젠가의 패배처럼",
	"이제 너에게 난 왕이 된다는 걸",
	"너를 이기면 할수록",
	"멀리 떠나가도록 — 신라도, 고구려도",
	"스치듯 시간의 흐름 속에",
	"너를 이기면 할수록",
	"멀리 떠나가도록",
	"스치듯 삼한의 흐름 속에",
]

# ── Gesomun · prayer to Heaven / Holy King, cruel means OK ──
SCENES["b1p0jQbpVi4"] = [
	"누구나 한번쯤은 하늘 앞에 무릎 꿇게 되는 순간이 있지",
	"그렇지만 나는 제자리로 오지 못했어 — 되돌아 나오는 길을 모르니",
	"너무 많은 생각과 너무 많은 걱정에 온통 내 자신을 가둬두었지",
	"이젠 이런 내 모습 나조차 불안해보여 — 어디부터 시작할지 몰라서",
	"나도 세상에 나가고 싶어 — 당당히 내 꿈들을 보여줘야 해",
	"그토록 오랫동안 움츠렸던 날개 — 하늘로 더 넓게 펼쳐 보이며",
	"날고 싶어 — 성왕님, 들어주소서",
	"감당할 수 없어서 버려둔 그 모든 건 나를 기다리지 않고 떠났지",
	"그렇게 많은 걸 잃었지만 후회는 없어 — 그래서 더 멀리 갈 수 있다면",
	"상처 받는 것보단 칼을 택한 거지 — 잔혹이 꼭 나쁜 것은 아니야",
	"외로움은 나에게 누구도 말하지 않을 소중한 걸 깨닫게 했으니까",
	"이젠 세상에 나갈 수 있어 — 당당히 내 꿈들을 보여줄 거야",
	"그토록 오랫동안 움츠렸던 날개 — 하늘로 더 넓게 펼쳐 보이며",
	"다시 새롭게 시작할 거야 — 더 이상 아무것도 피하지 않아",
	"이 나라 살릴 그 힘이 돼 줄 거야 — 하늘이여",
	"힘겨웠던 방황은 — 이제 전쟁이다",
]

# ── Gardener · cryptic flower-field jingle, dark past ──
SCENES["4u7kNELI76A"] = [
	"Someone grew these flowers before",
	"And I could tell you where I'm from",
	"The petal-count to put my mind at ease",
	"Please just have a laugh with me",
	"'Cause you know I'm borrowing by now",
	"These blooms have already crowned",
	"Come on, it's a silly dream",
	"Dreaming of the fields unfound",
	"The view sits nice from that cloud",
	"And if you want a piece of my past",
	"There's a coin worth flipping",
	"Why don't you toss?",
	"Please just have a laugh with me",
	"'Cause you know I'm borrowing by now",
	"These blooms have already crowned",
	"Come on, it's a silly dream",
	"Dreaming of the imagery unfound — don't ask who I was",
	"The view sits nice from that cloud",
	"And if you want a piece of my thoughts",
	"There's a coin worth flipping — careful",
	"Why don't you toss?",
]

# ── Three Princesses · Sacred Bone last three, personalities ──
SCENES["bYrF7cVi5vE"] = [
	"환상 속에 있어 — 덕만",
	"다가설 수 없는 별을 우리에게 별을 보여줘",
	"조금만 다가서도 — 승만",
	"멀어지는 나의 사랑, 나의 꿈",
	"내게 너를 맞춰가고 있다 말하지 마 — 천명",
	"나에겐 너희를 초대할 뿐이야",
	"신비로운 우리의 뼈, 우리에게는 생존인걸",
	"조금씩 다가오는 칼을 느낄수록",
	"신비로운 성골의 모습, 우리에게는 책임인걸",
	"조금씩 멈춰지는 시간 속의 셋",
	"어둠속의 빛처럼, my love — 세 자매",
	"다가설 수 없는 왕위를 내게 보여줘",
	"어둠 속의 한 줄기 빛처럼 느껴, my love",
	"사랑하는 나라를 모두 지킬 수 있어",
	"어둠 속의 빛처럼 — 마지막 셋",
	"내게 너를 맞춰가고 있다 말하지 마",
	"나에겐 너희를 초대할 뿐이야",
	"신비로운 성골의 모습, 우리에게는 살아남는 일",
]

# ── Sunduk → Yushin · I Believe ──
SCENES["GGr5ZzBanGU"] = [
	"그대 그약속을",
	"기억하고 있을까요 — 유신",
	"I believe I believe",
	"I believe",
	"많이 변했을 내 모습을",
	"알아볼까요",
	"And I believe",
	"I believe I believe",
	"니가 떠나던 날",
	"너의 빈 마당 위에",
	"새겨져 있던 그말을",
	"난 기억해요",
	"오늘이 바로 그대",
	"약속한 그날인걸요",
	"오지 못할거란걸",
	"알고 있어",
	"앞으로도 영원히",
	"볼 수 없다는 것을 — 아니, 와 줘",
	"이젠 이세상에",
	"너란 사람은 없는거니",
	"내가 잘못 안것이길",
	"빌고 있어",
	"우리 약속한",
	"이곳 에서 — 월지",
	"I, I, I, I, I believe, I believe",
	"I, I, I, I, I believe",
	"I believe I believe I believe woo",
	"I believe I believe",
	"I believe I believe I believe woo",
	"I believe I believe",
	"처음부터 운명이란 걸",
	"난 느꼈어요",
	"I believe I believe",
	"친근한 말 한 마디조차",
	"한 적 없지만",
	"And I believe",
	"슬픈 그대 얼굴",
	"이유를 알았을때",
	"애써 담담한 표정만",
	"짓고 있었 죠",
	"연락하기로 해",
	"웃으며 말하던",
	"너는 어디있니 — 마당에",
	"오지 못할거란걸",
	"알고 있어",
	"앞으로도 영원히",
	"볼 수 없다는 것을",
	"이젠 이세상에",
	"너란 사람은 없는거니",
	"내가 잘못 안것이길",
]

# ── Heo · Good Goodbye (Red Sail) ──
SCENES["Qe8fa4b5xNU"] = [
	"나를 그냥 짓밟고 가 — 수로야",
	"괜찮아 돌아보지 마",
	"내가 아파봤자 너만 하겠니",
	"이젠 너를 헤아려봐 — 뱃머리",
	"날 위해 쉬던 그 숨은 잊고",
	"저 위에 널 위해 just kill my ego",
	"등 돌려 걸어가 — 붉은 돛",
	"You got it you got it yeah",
	"안녕은 우릴 아프게 하지만 우아할 거야",
	"나 땅을 치고 후회하도록 넌 크게 웃어줘",
	"goodb-ye",
	"bye ye ye ye ye ye",
	"bye ye ye ye ye ye (b-ye)",
	"bye ye ye ye ye ye",
	"bye ye ye ye ye",
	"후회하도록 goodb-ye",
	"널 생각한 운율이야 — 가야까지의",
	"비로소 느껴지잖아",
	"눈물은 고이고 찬란하게 빛나",
	"우린 좋은 안녕 중이야",
	"고맙단 말 대신 전할게",
	"goodbye good goodbye",
	"안녕은 우릴 아프게 하지만 우아할 거야",
	"나 땅을 치고 후회하도록 넌 크게 웃어줘",
	"goodb-ye",
	"bye ye ye ye ye ye",
	"bye ye ye ye ye ye (b-ye)",
	"bye ye ye ye ye ye",
	"bye ye ye ye ye",
	"세상이 나를 빤히 내려다봐도",
	"내 편이 돼 줄 사람 하나 없어도",
	"Don't worry it's okay",
	"난 내 곁에 있을게 — 바다 위에서",
	"I'll be on my side instead of you",
	"안녕은 나를 아프게 하지만 울어볼 거야",
	"땅을 치고 후회해도 좋아 우리 이렇게",
	"goodb-ye",
	"bye ye ye ye ye ye",
	"bye ye ye ye ye ye (b-ye)",
	"bye ye ye ye ye ye",
	"bye ye ye ye ye",
	"후회조차도 goodb-ye",
]

# ── Sosuno · 대화가 필요해 (flirty fight with Jumong) ──
SCENES["t79LDdqsOi4"] = [
	"또 왜 그러는데 뭐가 못마땅한데 — 주몽",
	"할 말 있으면 터 놓고 말해봐",
	"너 많이 변했어 (내가 뭘 어쨌는데)",
	"첨엔 안 그랬는데 (첨에 어땠었는데)",
	"요새는 내가 하는 말투랑 화장과 머리 옷 입는 것까지",
	"다 짜증 나나봐 (그건 니 생각이야)",
	"우리 서로 사랑한지도 어느덧 — 우물부터",
	"매일 보는 얼굴 싫증도 나겠지",
	"나도 너처럼 나 좋다는 사람 많이 줄 섰어",
	"(간다는 사람 잡지 않아 어디 한번 잘해봐)",
	"근데 그놈의 정이 뭔지 내 뜻대로 안 돼",
	"맘은 끝인데 몸이 따르질 않아",
	"아마 이런 게 사랑인가봐 널 사랑하나봐",
	"(지금부터 내 말을 들어봐)",
	"넌 집착이 심해 (그건 집착이 아냐)",
	"나를 너무너무 구속해 (그럼 너도 나를 구속해)",
	"우리 결혼한 사이도 아닌데 마치 왕비처럼",
	"모든 걸 간섭해",
	"너의 관심 끌고 싶어서 내 정든 긴 머리",
	"짧게 치고서 웨이브 줬더니",
	"한심스러운 너의 목소리 나이 들어 보여",
	"(난 너의 긴 머리 때문에 너를 좋아했는데)",
	"니가 너무 보고 싶어서 전화를 걸어",
	"날 사랑하냐고 물어봤더니",
	"귀찮은 듯한 너의 목소리 나 지금 바빠",
	"(듣고 보니 내가 너무 미안해)",
	"대화가 필요해 (이럴 바엔 우리 헤어져)",
	"내가 너를 너무 몰랐어 (그런 말로 넘어가지 마)",
	"항상 내 곁에 있어서 너의 소중함과 고마움까지도",
	"다 잊고 살았어",
	"대화가 필요해 우린 대화가 부족해",
	"서로 사랑하면서도 사소한 오해 맘에 없는 말들로",
	"서로 힘들게 해 (너를 너무 사랑해)",
	"대화가 필요해 — 우물에서",
]

# ── Haemosu · BAE BAE (feral sun-god flirting Amnok sisters) ──
SCENES["TKD03uPVD-Q"] = [
	"🐲 I'm in love 눈에 콩깍지 씌었어 babe (Oh)",
	"하의 실종에 흰 와이셔츠 babe — 강물 babe (Oh)",
	"사람이야 천사야 oh Jesus, babe (Woh)",
	"눈부셔 babe (Woh)",
	"Sunglass babe",
	"정신이 망신이야 홀렸어 네게 (Yeh)",
	"피가 한쪽으로 또 쏠렸어 네게 (Right)",
	"위험해 you're so dangerous babe",
	"살려줘 babe",
	"경찰 불러 babe — 아니 동생들",
	"☀️ Baby, baby 지금처럼만",
	"아름다워 줄래 넌 — 유화",
	"시간이 지나도 내가 설렐 수 있게",
	"Woo",
	"Baby, baby 넌 시들지 마",
	"이기적인 날 위해",
	"그 모습 그대로",
	"넌 그대로 여야만 해",
	"🐰 Yeah",
	"사슴같이 예쁜 눈 나의 princess (Yeah)",
	"나를 보고 비웃는 게 너무 chic 해 (Yeah)",
	"미친 거 아닐까 자연 미인 특이해 특이해",
	"내게 완벽한 그대여 나의 muse 해",
	"우리 둘이 편해 완전 살찌네 (Right)",
	"너와 몸이 완전 착착 감기네 (Hoh)",
	"영원히 넌 스물다섯이야 내게 (Yeah)",
	"변치 않아 babe 오 곱하기 오 (5 X 5) babe",
	"🐯 Baby, baby 지금처럼만",
	"아름다워 줄래 넌",
	"시간이 지나도 내가 설렐 수 있게",
	"Woo",
	"Baby, baby 넌 시들지 마",
	"이기적인 날 위해",
	"그 모습 그대로",
	"넌 그대로 여야만 해",
	"🐼 난",
	"예쁜 꽃을 든 남자 — 태양",
	"모든 이가 사랑할",
	"너란 꽃을 든 남자",
	"그대 향기에 취해",
	"난 또 몽롱해지고",
	"꺾이지 말아주오",
	"제발 너만은 — 막내",
	"🐲 찹쌀떡 (Oh, right)",
	"찹쌀떡 (Woo, 🐰 babe babe)",
	"궁합이 Yeah",
	"우리 우리 궁합이 (Haha)",
	"Yeah (Bae babe, babe bea)",
	"찹쌀떡 (Oh, 🐰 babe babe)",
	"찹쌀떡 (WOO!, Blow blow)",
	"궁합이 Yeah",
	"우리 우리 궁합이 (Haha)",
	"Yeah",
]

# ── Yushin → Dukman · Always ──
SCENES["Ztu7uW6U93Y"] = [
	"This Romeo is bleeding",
	"But you can't see his blood",
	"It's nothing but some feelings",
	"That this old dog kicked up — for Dukman",
	"It's been raining since you left me",
	"Now I'm drowning in the flood",
	"You see, I've always been a fighter",
	"But without you, I give up",
	"I can't sing a love song",
	"Like the way it's meant to be",
	"Well, I guess I'm not that good anymore",
	"But baby, that's just me",
	"And I will love you, baby, always — Princess",
	"And I'll be there forever and a day, always",
	"I'll be there 'til the stars don't shine",
	"'Til the heavens burst and the words don't rhyme",
	"And I know when I die, you'll be on my mind",
	"And I'll love you, always",
	"Now your pictures that you left behind",
	"Are just memories of a different life",
	"Some that made us laugh, some that made us cry",
	"One that made you have to say goodbye — the crown",
	"What I'd give to run my fingers through your hair",
	"To touch your lips, to hold you near",
	"When you say your prayers, try to understand",
	"I've made mistakes, I'm just a man — a marshal",
	"When he holds you close, when he pulls you near",
	"When he says the words you've been needing to hear",
	"I wish I was him",
	"With these words of mine",
	"To say to you 'til the end of time",
	"That I will love you baby, always",
	"And I'll be there forever and a day, always",
	"If you told me to cry for you, I could",
	"If you told me to die for you, I would — Hwangsan",
	"Take a look at my face",
	"There's no price I won't pay",
	"To say these words to you",
	"Well, there ain't no luck",
	"In these loaded dice",
	"But baby, if you give me just one more try",
	"We can pack up our old dreams",
	"And our old lives",
	"We'll find a place where the sun still shines",
	"And I will love you, baby, always",
	"And I'll be there forever and a day, always",
	"I'll be there 'til the stars don't shine",
	"'Til the heavens burst and the words don't rhyme",
	"I know when I die, you'll be on my mind",
	"And I'll love you, always",
	"Always, always — Dukman",
]

# ── Jahee · Nagging (Bupmin) ──
SCENES["7_JEkO6KvVo"] = [
	"늦게 다니지좀 마 — 문무",
	"술은 멀리좀 해봐",
	"열살짜리 애처럼 말을 안듣니",
	"정말 웃음만 나와",
	"누가 누굴보고 아이라 하는지",
	"정말 웃음만 나와",
	"늦게 다니지좀 마",
	"술은 멀리좀 해봐",
	"열살짜리 애처럼 말을 안듣니",
	"정말 웃음만 나와",
	"누가 누굴보고 왕이라 하는지",
	"정말 웃음만 나와",
	"오늘도 잔소리야",
	"내일도 잔소리야",
	"그래도 내 옆에 있어줘",
	"잔소리야",
	"잔소리야",
	"그래도 사랑이야",
	"문무야",
	"내 말 좀 들어",
]

# Fix nagging count dynamically below if wrong

# ── Pumsuk · Nerdy Love (Gotaso) ──
SCENES["FFkLoUwQ9a4"] = None  # filled below

# ── Haemosu · 고해 (Yuhwa) ──
SCENES["se54TCtTFsQ"] = None

# ── Little Fall · My Queen ──
SCENES["mu_little_fall_of_rain"] = None

# ── Bidam · GYBR (leaving the yellow brick of court) ──
SCENES["XWFjoZ41Mm8"] = [
	"When are you gonna come down?",
	"When are you going to land?",
	"I should have stayed in the temple",
	"I should have listened to my old beads",
	"You know you can't hold me forever — Queen",
	"I didn't sign up with you",
	"I'm not a present for your friends to open",
	"This boy's too young to be singing the blues",
	"So goodbye yellow brick road",
	"Where the dogs of society howl — True Bone",
	"You can't plant me in your penthouse",
	"I'm going back to my plough — the rebellion",
	"Back to the howling old owl in the woods",
	"Hunting the horny back toad",
	"Oh, I've finally decided my future lies",
	"Beyond the yellow brick road",
	"What do you think you'll do then",
	"I bet that'll shoot down your plane",
	"It'll take you a couple of vodka and tonics",
	"To set you on your feet again",
	"Maybe you'll get a replacement",
	"There's plenty like me to be found",
	"Mongrels who ain't got a penny",
	"Sniffing for tidbits like you on the ground",
	"So goodbye yellow brick road",
	"Where the dogs of society howl",
	"You can't plant me in your penthouse",
	"I'm going back to my plough",
	"Back to the howling old owl in the woods",
	"Hunting the horny back toad",
	"Oh, I've finally decided my future lies",
	"Beyond the yellow brick road — Sunduk",
]


def apply(track_id: str, scenes: list[str]) -> None:
	path = OUT / f"{track_id}.json"
	data = json.loads(path.read_text())
	vocals = [l for l in data["lines"] if l.get("text", "").strip() != NOTE]
	if len(scenes) != len(vocals):
		raise SystemExit(
			f"{track_id}: scene count {len(scenes)} != vocals {len(vocals)}"
		)
	vi = 0
	for line in data["lines"]:
		if line.get("text", "").strip() == NOTE:
			line.pop("scene", None)
			continue
		scene = scenes[vi].strip()
		vi += 1
		if scene == line["text"].strip():
			# still set so UI knows it's "adapted" but identical is fine — skip identical
			# to keep toggle meaningful only when different
			line.pop("scene", None)
		else:
			line["scene"] = scene
	path.write_text(json.dumps(data, ensure_ascii=False, indent="\t") + "\n")
	diff = sum(1 for l in data["lines"] if l.get("scene"))
	print(f"OK {track_id}: {diff}/{len(vocals)} scene lines")


def main() -> None:
	for tid, scenes in SCENES.items():
		apply(tid, scenes)


if __name__ == "__main__":
	main()
