"""Dynamic-angle rewrite of the still-bare notable slots; action beats also take the manga action-frame text."""
import json

SRC = 'scripts/.cache/notable-stills-manifest.json'
OUT = 'scripts/.cache/dynamic-pass-manifest.json'
MANGA = open('scripts/.cache/manga-action.txt').read().strip()
CROP = 'Composed for a 2:1 letterbox crop; nothing important at the top or bottom edge.'

# id -> (scene, action?)
SCENES = {
    'exile-queen-bier': ('Crane shot straight down from the rafters of a night mourning hall in Sabi, hard dutch rotation: Queen Satek lies in state under white hemp on a bier, censer smoke curling up toward the lens; at its foot Euija kneels in coarse undyed hemp mourning clothes over his court robe, a straw cord on his head, forehead almost to the floor but his eyes open and furious. At the edge of the frame an official’s sleeve carries the lacquered royal seal box out of the light. One lamp at the foot of the bier throws long shadows across the floorboards.', False),
    'exile-gate-count': ('Worm’s-eye from the wet stone steps of a mountain monastery gate at night in rain, hard dutch tilt, looking up through the timber gate with its giwa roof: two clan retinues stand in facing lines towering on either side, one house in dark teal sashes, the other in rust-red; two stewards with lanterns lean down into the lens counting men on raised fingers, each counting the other side. Rain streaks catch the lanterns; the gate’s dark doorway splits the two lines.', False),
    'exile-lantern-festival': ('Lantern festival night on a Sabi street a year earlier, mid-brawl, hard dutch tilt: a burning paper lotus lantern falls straight at the lens in extreme foreshortening, sparks flying; behind it a youth in rust-red silk swings a fist through the air and a young man in teal silk reels back clutching his side; the crowd scatters into warm bokeh. No blood, no gore.', True),
    'exile-footprints': ('Extreme low angle with the lens on the dusty floorboards behind a paper monastery screen at night: a servant’s hand lowers a lamp into the sharp foreground, and a second set of small, careful footprints runs from the lens across the pool of light toward a narrow back door left ajar. Through the translucent screen, the blurred silhouettes of two old clan elders at wine. Dutch tilt. No writing on the screen.', False),
    'exile-shape-of-fight': ('Bird’s-eye straight down on a monastery courtyard at night after rain, rotated on a hard diagonal: two clusters of retainers stand apart on wet flagstones, unconsciously arranged as two facing wedges, torches in a few hands, long shadows reaching toward each other; a single bar of warm light from one lit lattice window lies in the empty strip between them.', False),
    'exile-name-offer': ('Top-down overhead shot onto the floor of a clan chamber at night, hard dutch rotation: in the centre a lacquered tray of rolled genealogy scrolls tied with cord and a small blank ancestral tablet, an oil dish burning beside it; Elder Satek’s hands push the tray forward from the left; on the right Gyebek kneels with his fists on his knees, not touching it, his face tilted up toward the lens, jaw set. Their shadows stretch away across the floorboards. No visible writing.', False),
    'exile-tent-arrow': ('Inside an army tent at the Ungjin drill ground at dusk: an arrowhead bursts through the canvas wall straight at the lens in extreme foreshortening, a torn star of hard gold light around it; behind it a tall officer is thrown back out of frame, and Gyebek drops into a low coiled crouch, hand on his sword hilt, eyes snapping to the hole. A hanging lamp swings, smearing light. No gore.', True),
    'exile-watched-cooking': ('Worm’s-eye up through the flames of a brazier in a smoky army kitchen at night, the fire in the sharp foreground: beyond the flames Gyebek sits on a low stool, arms folded, staring down unblinking into the pot; the nervous cook leans over it stirring, sweat on his face. Embers rise toward the lens as bokeh; smoke curls under the rafters. Dutch tilt.', False),
    'exile-seongchung': ('Low dutch angle along a night colonnade of the Sabi palace: Seongchung, the old minister, lunges into the foreground and grabs Gyebek’s forearm with both hands, his knuckles huge and foreshortened toward the lens, mouth open mid-plea; Gyebek, half turned away, looks down the dark corridor of receding pillars, unmoved. One hanging lantern swings between them; their shadows slash across the floorboards.', False),
    'exile-berth': ('High crane shot from the mast-top looking straight down at Sabi port at pre-dawn, river mist: Gyebek, small, walks up the gangplank onto the deck alone, carrying nothing; the captain at the rail turns away; on the quay Minister Satek stands in dark silk with a hand on the seal pouch under his sleeve, looking up. One lantern on the quay post throws long shadows across the wet planks.', False),
    'talhae-chest-tide': ('Wave-level shot with the lens half in the surf at storm dawn off the rocky shore of Ajinpo, hard dutch tilt: a lacquered wooden chest rides the crest of a breaking wave straight at the camera; above it a magpie dives toward the lens, wings spread and crying. Spray flies; one low gold cloud-break lights the chest and the bird.', False),
    'talhae-feathers': ('Inside King Suro’s torchlit Gaya hall at night, worm’s-eye from the floor, hard dutch tilt: a burst of brown sparrow feathers explodes outward around Talhae as he lands back in his own body, already dropping into a lopsided bow, grinning; behind and above him on the dais King Suro, falcon feathers still swirling off his shoulders, grips the throne arms, pale with relief. Feathers fly at the lens.', True),
    'talhae-old-woman': ('Top-down shot straight into an opened lacquered chest on the Ajinpo sand at dusk: among gold and folded silk a small boy sits looking straight up into the lens, unbothered; the old fisherwoman’s weathered face and hand on the lid lean into the frame edge from above, her rope across the sand; a magpie perched on the lid. Low sun rakes across the gold.', False),
    'talhae-whetstone': ('Ground-level shot through tall grass at night, hard dutch tilt, on a crescent rise above the river: young Talhae crouches at the foot of a minister’s timber gate, scooping earth with both hands over a whetstone and a charcoal sack, glancing back over his shoulder straight into the lens with a sly grin. A paper lantern over the gate is the warm key; cold moonlight on the giwa roof edge.', False),
    'talhae-prove-it': ('Worm’s-eye from inside a freshly dug hole at the minister’s gate in low morning sun: the whetstone and charcoal lie black on the rim in the sharp foreground; above, magistrate’s men lean on spades, old Hogong, gourd at his waist, points down at Talhae in trembling outrage, and Talhae looks down into the hole with arms folded, deadpan. Long raking shadows.', False),
    'alji-sirim-box': ('Worm’s-eye from the forest floor of the Sirim wood at dawn, looking straight up through dark trunks: a small golden box hangs from a branch overhead catching the first shaft of light; a white rooster below it crows straight at the lens, beak wide; old Hogong freezes at the frame edge with a lantern he no longer needs. Mist drifts across the shaft.', False),
    'alji-box-open': ('Point of view from inside the opened golden box looking up: old King Talhae, short grey beard, leans down over the rim grinning, his face foreshortened and huge; at the bottom edge of the frame the small boy’s tiny hand and white silk sleeve reach up. Courtiers lean in blurred behind the king; a lattice shaft of morning light falls past him into the box.', False),
    'alji-steam': ('Under a hill beyond the city: an empty steam cavern at night, low angle from the water surface, black still water in a stone bowl, a single plume of steam lifting off it into one thin shaft falling through a crack above. A few drifting motes in the steam: one ember-orange, one cyan, one leaf-green. No figures. 85% of the frame black wet stone.', False),
    'seohyun-third-pass': ('Low dutch angle from the stone threshold of a grand timber gate in late afternoon: Manmyung leans against the gate post in the near foreground, arms folded, eyebrow raised, hiding a smile, looking out; beyond her Seohyeon rides past in the street for the third time, twisting in the saddle to look back. Long low shadows rake the street between them.', False),
    'seohyun-crawl': ('Worm’s-eye from the mud at the base of an earth-and-stone wall in a night storm: Manmyung crawls through a low gap straight toward the lens, soaked good silk dragging, face set; behind her a lightning bolt strikes the guarded door in a white flash, guards ducking. Rain streaks slash across the frame.', True),
    'seohyun-ride-north': ('Low tracking shot at hoof height on a muddy road out of Surabol at night in thinning rain, hard dutch tilt: Seohyeon rides hard with Manmyung up behind him, her arms around his waist, her muddy silk streaming, laughing into his back; the horse’s legs and flung mud smear past the lens; the city’s gate lanterns streak into bokeh behind; one storm break lights the road ahead.', True),
    'seohyun-fall': ('Magical cavern atmosphere, steam and motes, anime-painterly cavern spirit, not photoreal, no body halo. Worm’s-eye from just under the surface of a black steaming pool: Seohyeon plunges feet-first down through a hole of light into the water above the lens in a burst of splash, soaked travel clothes and sword still in his hand; at the edge of the frame on the far wet rock three young women in white jeogori and character-colour chima lean in to look — Golhwa legs apart grinning, Hyullé knees pressed together peeking, Narim upright. Ember, cyan and leaf motes scatter in the steam.', True),
    'seohyun-oracle': ('Oracle pronouncement. Low worm’s-eye from the water line, hard dutch tilt: the three sisters loom on the rock above, their ENTIRE eyes solid glowing colour — Narim #3d9e52, Hyullé #2eb8c4, Golhwa #e86820 — the whole eye, eyes only, no body aura. Their faces are serious now. Seohyeon small and still in the steaming water in the lower foreground, back to us. Steam and motes; 80% dark wet stone.', False),
    'seohyun-warm-stone': ('Over-the-shoulder from behind Seohyeon kneeling just inside the door of a small governor’s house at Manno at night, dutch tilt: his hand in the near foreground turns a warm grey river stone half out of his sleeve; across the floor Manmyung sits up on the quilt with the baby asleep on her arm, squinting at him with suspicion and amusement. One oil dish on the floor between them; their shadows climb the screen wall.', False),
}

items = []
for it in json.load(open(SRC)):
    if it['id'] not in SCENES:
        continue
    scene, action = SCENES[it['id']]
    it['scene'] = ' '.join(filter(None, [scene, MANGA if action else '', CROP]))
    it.pop('prompt', None)
    it.pop('after', None)
    items.append(it)
assert len(items) == len(SCENES), (len(items), len(SCENES))
json.dump(items, open(OUT, 'w'), ensure_ascii=False, indent=1)
print(len(items), '->', OUT)
