// The intro-card look (painted webtoon splash), shared by character intro stills and scene stills.

const FRAME = `A 2:1 movie frame composed for a 2:1 letterbox crop (nothing important at the top or bottom edge).`;

const BRUSH = `EVERYTHING ELSE IS PAINTED: visible textured brushwork — loose digital-paint strokes and dry-brush, charcoal-like hatching that follow every fold of the silk and every plate of armour, the shadows built from layered strokes, the brightest ridges laid in with single confident strokes, a faint paper-and-canvas grain; at the edges of the garments the linework breaks into loose sketchy strokes. NOT flat cel-shading, NOT smooth airbrushed gradients, NOT a clean vector look, NOT photoreal, NOT 3D.`;

const BACKGROUND = `the background IS the place and the moment of the scene — open sky if they are in the sky, the hall if they are in a hall, the gate, the river, the snow — painted loosely in atmospheric brushwork (drifting smoke, cloud, haze, mist, falling snow, embers) in the scene's own colours, soft and out of focus, with a faint bokeh of small lights; it has colour, weather and depth — never a flat black void, never a detailed set`;

const KEY = `ONE hard directional key light that belongs to the place (a brazier, a lamp, the sun through cloud, a torch, moonlight) rakes across the faces and clothes from the side or from below, modelling them in high contrast with deep painted shadows and a thin edge of the same light along the silhouette. Each character's colour lives in that light and in the atmosphere around them — never a glow aura or halo.`;

const CLEAN = `No text, no speech bubbles, no panel borders, no watermark.`;

export const INTRO_OPEN = `HEEWON STYLE — a KOREAN WEBTOON character-introduction splash PAINTED like a premium digital painting, the look of a dramatic manhwa cover. ${FRAME} MEDIUM CLOSE SHOT of ONE character — waist-up or seated — the face large and razor-sharp, placed off-centre on a third with breathing room on the side they look toward, seen from a dramatic camera angle (low three-quarter, worm's-eye or over-the-shoulder), never a flat straight-on catalogue pose. THE FACE is drawn exactly like the attached character sheet: the same clean confident ink linework and manhwa face design (eye shape, brows, nose, jaw, hairline and hair), recognisably that character, wearing the same clothes. ${BRUSH}`;

export const INTRO_TAIL = `BACKGROUND AND LIGHT (painterly tenebrism): ${BACKGROUND}, never a crowd. ${KEY.replace('the faces and clothes', 'the face and clothes').replace("Each character's colour", "The character's colour")} The FACIAL EXPRESSION and BODY LANGUAGE carry the line they are about to say. Face and clothes from the sheet; a new pose, never the sheet's stance. ONLY THIS ONE PERSON is the subject — anyone else is at most a dark out-of-focus shape at the frame edge, dressed in period clothing of their own court (Korean, Tang or Yamato), never European dress. ${CLEAN}`;

export const SCENE_OPEN = `HEEWON STYLE — a KOREAN WEBTOON movie still PAINTED like a premium digital painting, the look of a dramatic manhwa cover. ${FRAME} The shot the scene names (wide establishing, two-shot, close-up, over-the-shoulder) from a dramatic camera angle (low three-quarter, worm's-eye, high overhead or dutch), never a flat straight-on catalogue pose. Named characters' FACES are drawn exactly like the attached character sheet: the same clean confident ink linework and manhwa face design (eye shape, brows, nose, jaw, hairline and hair), recognisably those characters, in the clothes the scene gives them. ${BRUSH}`;

export const SCENE_TAIL = `BACKGROUND AND LIGHT (painterly tenebrism): ${BACKGROUND}; crowds and armies only as massed painted shapes dissolving into haze. ${KEY} Faces and bodies act the beat: real expressions, real weight, mid-motion. Faces from the sheet; new poses, never the sheet's stance. Each named person appears once, never cloned. Everyone wears period clothing of their own court (Korean, Tang, Yamato, Mohe furs), never European dress. ${CLEAN}`;
